CREATE TABLE IF NOT EXISTS LAMP_USERS (
    USER_ID INTEGER,
    USER_NAME VARCHAR(40),
    USER_PASSWORD VARCHAR(40),
    REGISTRATION_DATE DATE,
    PRIMARY KEY(USER_ID)
);


CREATE TABLE IF NOT EXISTS LAMP_PROJECTS(
    PROJECT_ID INTEGER,
    PROJECT_NAME VARCHAR(100),
    USER_ID INTEGER REFERENCES LAMP_USERS (USER_ID),
    PRIMARY KEY(PROJECT_ID)
);


CREATE TABLE IF NOT EXISTS LAMP_PROMPTS(
    PROMPT_ID INTEGER,
    PROMPT VARCHAR(1000),
    PROJECT_ID INTEGER REFERENCES LAMP_PROJECTS (PROJECT_ID),
    PRIMARY KEY(PROMPT_ID)
);


CREATE TABLE IF NOT EXISTS LAMP_RESULTS(
    CODE_ID INTEGER,
    RESULT_FUNC VARCHAR(5000),
    RESULT_DATE DATE,
    PROJECT_ID INTEGER REFERENCES LAMP_PROJECTS (PROJECT_ID),
    PROMPT_ID  INTEGER REFERENCES LAMP_PROMPTS (PROMPT_ID),
    PRIMARY KEY(CODE_ID)
);


INSERT INTO LAMP_USERS VALUES (1, 'test-user', 'qwerty1234', '1970-01-01'::date);
